name: Release (Windows)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Ensure icon
        run: |
          if (Test-Path assets/icon/verdant.ico) { echo 'icon exists' } else { python tools/make_icon.py }

      - name: Build VerdantApp.exe
        run: |
          pyinstaller --noconfirm `
            --onefile `
            --name VerdantApp `
            --windowed `
            --add-data "presets.json;." `
            --collect-all llama_cpp `
            --icon assets/icon/verdant.ico `
            verdant_app.py

      - name: Build VerdantUpdater.exe
        run: |
          pyinstaller --noconfirm `
            --onefile `
            --name VerdantUpdater `
            --console `
            --icon assets/icon/verdant.ico `
            tools/verdant_updater.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: |
            dist/VerdantApp.exe
            dist/VerdantUpdater.exe

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/VerdantApp.exe
            dist/VerdantUpdater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 