name: Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate app icon
        run: |
          python tools/make_icon.py

      - name: Build EXE
        shell: bash
        run: |
          pyinstaller --noconfirm \
            --onefile \
            --name VerdantApp \
            --add-data "presets.json;." \
            --collect-all llama_cpp \
            --icon assets/icon/verdant.ico \
            verdant_app.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/VerdantApp.exe
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 