name: Release Windows EXE (disabled)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    if: false
    runs-on: windows-latest
    steps:
      - name: No-op
        run: echo Disabled 